### ISSUE TITLE
Update host detail graphs in real time

### ISSUE THREAD

**Issue by psiniemi** [NitorCreations/willow#55]
All nv.d3 graphs should register to get updates via websocket the same way the alerts window does.

**Comment by psiniemi** [comment]
https://github.com/novus/nvd3/blob/master/test/realTimeChartTest.html

**Comment by psiniemi** [comment]
I was thinking that this probably needs some kind of id to match updates with the original request. I could add that to the server side...

**Comment by mlison** [comment]
Oh, you're probably right. It should be added as a param when configuring the socket.
